### ISSUE TITLE
Unable to write contents to file

### ISSUE THREAD

**Issue by dawpud** [matheusccastroo/vscode-meteor-toolbox#2]
Any time this extension tries to write to the jsconfig.json file, it throws an error saying it is unable to write to the file. However, the file path has an extra /C: at the beginning so, the path is "/C:/c:/...". A screenshot is below:
![image](https://user-images.githubusercontent.com/103465827/175869729-e4e9269d-3590-47dd-88db-20b0d3349e6e.png)
Is there a setting that can be tweaked to change this file path? Thanks!

**Comment by matheusccastroo** [comment]
Hello, @dawpud!
No, unfortunately that seems to be an issue on the path resolver for windows. Are you on Windows 10?
Will check it here but probably only at the end of this week.

**Comment by dawpud** [comment]
Hey @matheusccastroo thanks for getting back to me! Yes, I am using windows 10.

**Comment by matheusccastroo** [comment]
@dawpud Just released version 1.1.5, it should fix this issue. Would you mind checking, please?

**Comment by dawpud** [comment]
@matheusccastroo So far, everything looks good. I am not getting the error anymore and I am getting confirmation that the extension successfully added packages to the jsconfig file. Thanks again!
