### ISSUE TITLE
setting to ignore/exclude files and folders from being indexed and parsed

### ISSUE THREAD

**Issue by bramdewitte** [matheusccastroo/vscode-meteor-toolbox#6]
There's one folder in our project that contains non-valid HTML.
When i enable the extension i get a couple of errors like this: 
`Error parsing file file:///home/.../.../filename.html. Error: Error: Unexpected HTML close tag ...`

Followed by:
`[Error - 10:08:45 AM] Server initialization failed.
  Message: Request initialize failed with message: Cannot read properties of undefined (reading 'uri')
  Code: -32603`

`[Error - 10:08:45 AM]Meteor Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: Cannot read properties of undefined (reading 'uri')
  Code: -32603 `

`[Error - 10:08:45 AM] Restarting server failed
  Message: Request initialize failed with message: Cannot read properties of undefined (reading 'uri')
  Code: -32603 `

`[Error - 10:08:47 AM] The Meteor Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.`

I found that removing the whole folder fixes the issue and lets me use the extension, but a setting to ignore/exclude the folder would be amazing.

**Comment by matheusccastroo** [comment]
@bramdewitte Unfortunately the Handlebars parser disagree with HTML sometimes of what is valid or not. The spacebars one is even more restrictive.

You are right, having a setting to ignore some folders from indexing would be good. Will work on it here.

**Comment by matheusccastroo** [comment]
@bramdewitte Added the option, it's on the 1.2.1 release!
