### ISSUE TITLE
Conflict with React Class component properties

### ISSUE THREAD

**Issue by rj-david** [matheusccastroo/vscode-meteor-toolbox#9]
When using this tool in React Class components, it conflicts with the component properties, e.g. `this.property`

I can no longer jump (Ctrl + click) to the reference of the property within the file which is very much needed in Class components

**Comment by matheusccastroo** [comment]
Hello, @rj-david!

Thanks for reporting, this is probably because of the typescript-server-plugin we have now. Will check it here.

**Comment by matheusccastroo** [comment]
@rj-david The fix is out on version 1.3.3!
